import { defineConfig } from 'vitepress'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const SITE = 'https://aaronaust1n.github.io'
const __dirname = path.dirname(fileURLToPath(import.meta.url))

/* Stats are generated by scripts/generate-stats.js before dev/build. */
function readStats() {
  try {
    return JSON.parse(fs.readFileSync(path.join(__dirname, 'stats.json'), 'utf8'))
  } catch {
    return { museum: { exhibits: '—', departments: '—' }, posts: { en: 0, zh: 0 } }
  }
}
const stats = readStats()

/* -------------------------------------------------------------------------- */
/* Data-driven helpers: sidebar + hreflang pairs are generated from the       */
/* markdown files so new posts are picked up automatically.                   */
/* -------------------------------------------------------------------------- */

const NON_POST_FILES = new Set(['index.md', 'tags.md', 'hello-world.md'])

/** Minimal frontmatter reader (title / date / description / image). */
function readFrontmatter(file) {
  const raw = fs.readFileSync(file, 'utf8')
  const fm = {}
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (match) {
    for (const line of match[1].split(/\r?\n/)) {
      const kv = line.match(/^([A-Za-z_][\w-]*):\s*"?([^"\n]*)"?\s*$/)
      if (kv) fm[kv[1]] = kv[2].trim()
    }
  }
  return fm
}

function postFiles(dir) {
  const full = path.join(__dirname, dir)
  if (!fs.existsSync(full)) return []
  return fs
    .readdirSync(full)
    .filter((f) => f.endsWith('.md') && !NON_POST_FILES.has(f))
    .map((f) => ({ file: f, fm: readFrontmatter(path.join(full, f)) }))
}

/** Map a relative source path (e.g. `zh/posts/foo.md`) to its site URL. */
function pageUrl(relativePath) {
  const noExt = relativePath.replace(/\.md$/, '')
  if (noExt.endsWith('index')) return noExt.replace(/index$/, '') || '/'
  return `/${noExt}.html`
}

function buildSidebar(postsDir, linkPrefix) {
  return [
    {
      text: 'Recent Posts',
      items: postFiles(postsDir)
        .sort((a, b) => (b.fm.date || '').localeCompare(a.fm.date || ''))
        .map(({ file, fm }) => ({
          text: fm.title || file.replace('.md', ''),
          link: `${linkPrefix}/${file.replace(/\.md$/, '')}`
        }))
    }
  ]
}

const enSidebar = buildSidebar('../posts', '/posts')
const zhSidebar = buildSidebar('../zh/posts', '/zh/posts')

/** The translation pair for a page, e.g. `posts/foo.md` <-> `zh/posts/foo.md`. */
function pairUrl(relativePath) {
  const isZh = relativePath.startsWith('zh/')
  const other = isZh ? relativePath.slice(3) : `zh/${relativePath}`
  const otherFile = path.join(__dirname, '../', other)
  if (!fs.existsSync(otherFile)) return null
  return { en: pageUrl(isZh ? other : relativePath), zh: pageUrl(isZh ? relativePath : other) }
}

/* -------------------------------------------------------------------------- */

export default defineConfig({
  title: "AaronAust1n",
  description: "A Personal Blog, record my thoughts and ideas, and share my knowledge and experiences. Wait for the world to be rebuilt by AGI. And save a copy for myself.",
  lastUpdated: true,

  // Per-page SEO: canonical, hreflang pairs for this page only, and richer
  // Open Graph / Twitter tags (previously every page carried 40 site-wide
  // alternate links and a large_image card without any image).
  transformHead: ({ pageData }) => {
    const head = []
    const fm = pageData.frontmatter || {}
    const relativePath = pageData.relativePath || ''
    const isZh = relativePath.startsWith('zh/')
    const url = pageUrl(relativePath)

    head.push(['link', { rel: 'canonical', href: SITE + url }])
    head.push(['meta', { property: 'og:url', content: SITE + url }])
    head.push(['meta', { property: 'og:site_name', content: 'AaronAust1n' }])
    head.push(['meta', { property: 'og:locale', content: isZh ? 'zh_CN' : 'en_US' }])

    const isArticle = /(^|\/)posts\//.test(relativePath) && !/tags\.md$|index\.md$/.test(relativePath)
    head.push(['meta', { property: 'og:type', content: isArticle ? 'article' : 'website' }])

    const title = fm.title || 'AaronAust1n'
    const description = fm.description || (isZh
      ? `个人博客与一座收录 ${stats.museum.exhibits} 件视觉实验的交互博物馆。`
      : `A personal blog and an interactive museum of ${stats.museum.exhibits} visual experiments.`)
    head.push(['meta', { property: 'og:title', content: title }])
    head.push(['meta', { property: 'og:description', content: description }])

    if (isArticle && fm.date) {
      head.push(['meta', { property: 'article:published_time', content: fm.date }])
    }
    if (Array.isArray(fm.tags)) {
      fm.tags.forEach((tag) => head.push(['meta', { property: 'article:tag', content: tag }]))
    }
    if (fm.keywords) {
      head.push(['meta', { name: 'keywords', content: fm.keywords }])
    }

    const image = fm.image ? (fm.image.startsWith('http') ? fm.image : SITE + fm.image) : null
    if (image) {
      head.push(['meta', { property: 'og:image', content: image }])
      head.push(['meta', { name: 'twitter:image', content: image }])
    }

    head.push(['meta', { name: 'twitter:card', content: image ? 'summary_large_image' : 'summary' }])
    head.push(['meta', { name: 'twitter:title', content: title }])
    head.push(['meta', { name: 'twitter:description', content: description }])

    const pair = pairUrl(relativePath)
    if (pair) {
      head.push(['link', { rel: 'alternate', hreflang: 'en', href: SITE + pair.en }])
      head.push(['link', { rel: 'alternate', hreflang: 'zh-CN', href: SITE + pair.zh }])
      head.push(['link', { rel: 'alternate', hreflang: 'x-default', href: SITE + pair.en }])
    }

    return head
  },

  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/logo.svg' }],
    ['meta', { name: 'google-site-verification', content: '7qOTQI0S3WKsYoD1raJBVSPNzUVUo-J3hLqeGLcpL_0' }]
  ],

  // Internationalization Configuration

  locales: {
    root: {
      label: 'English',
      lang: 'en'
    },
    zh: {
      label: '简体中文',
      lang: 'zh-CN',

      // localized theme config
      themeConfig: {
        nav: [
          { text: '首页', link: '/zh/' },
          { text: '博客', link: '/zh/posts/' },
          { text: '博物馆', link: '/museum/', target: '_self' },
          { text: '标签', link: '/zh/posts/tags' },
          { text: '投票', link: '/zh/vote' }
        ],

        sidebar: zhSidebar,

        footer: {
          message: '基于 MIT 许可发布。',
          copyright: '版权所有 © 2026 AaronAust1n'
        },

        docFooter: {
          prev: '上一页',
          next: '下一页'
        },

        outline: {
          label: '本页目录',
          level: [2, 4]
        },

        lastUpdated: {
          text: '最后更新于',
          formatOptions: {
            dateStyle: 'short',
            timeStyle: 'medium'
          }
        },

        langMenuLabel: '多语言',
        returnToTopLabel: '回到顶部',
        sidebarMenuLabel: '菜单',
        darkModeSwitchLabel: '主题',
        lightModeSwitchTitle: '切换到浅色模式',
        darkModeSwitchTitle: '切换到深色模式'
      }
    }
  },

  themeConfig: {
    // Shared config
    logo: '/logo.svg',

    socialLinks: [
      { icon: 'github', link: 'https://github.com/AaronAust1n/AaronAust1n.github.io' }
    ],

    // Enable deep outline for all pages
    outline: {
      level: [2, 4], // Show h2 to h4 in the outline
      label: 'On this page'
    },

    // Default (English) config
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Blog', link: '/posts/' },
      { text: 'Museum', link: '/museum/', target: '_self' },
      { text: 'Tags', link: '/posts/tags' },
      { text: 'Vote', link: '/vote' }
    ],

    sidebar: enSidebar,

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © 2026 AaronAust1n'
    }
  }
})
